spring.application.name=QrApplication

server.address=0.0.0.0

logging.file.name=/opt/tomcat/latest/logs/QR_BACK.log
#logging.level.org.springframework.web.socket=DEBUG
#logging.level.org.springframework.messaging.simp=DEBUG
#logging.level.org.springframework.web.socket.sockjs=DEBUG

# DataSource configuration
#spring.datasource.url=jdbc:postgresql://13.235.82.153:5432/QrAppLive
spring.datasource.url=jdbc:postgresql://localhost:5432/QrApplication
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate configuration
spring.jpa.hibernate.ddl-auto=update

#product.image.dir=/opt/QR_APP_PRODUCT_IMAGE/
product.logo.dir:/home/ubuntu/logo/
product.image.dir=/home/ubuntu/QR_APP_PRODUCT_IMAGE/
product.invoice.dir=/home/ubuntu/invoice/
#twilio.account_sid=
#twilio.phone_number=
#twilio.auth_token=

#product.invoice.dir=D:/test/
#product.logo.dir:D:/test/
#product.image.dir=D:/QR_APP_PRODUCT_IMAGE/

management.endpoint.info.enabled=true
logging.config=classpath:logback-spring.xml
-Dlogging.config=classpath:logback-spring.xml
