spring.application.name=QrApplication

# DataSource configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/QrApplication
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate configuration
spring.jpa.hibernate.ddl-auto=update

logging.level.org.springframework.security=DEBUG
server.servlet.session.timeout=30m
